/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TestSuiteVO } from './testSuiteVO';


export interface TestRunVO { 
    applicationId?: number;
    applicationName?: string;
    applicationVersion?: string;
    browser?: string;
    environmentId?: number;
    environmentName?: string;
    executedBy?: string;
    executionStart?: Date;
    id?: number;
    name?: string;
    operatingSystem?: string;
    systemIp?: string;
    systemName?: string;
    testSuites?: Array<TestSuiteVO>;
}
