/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TestStepAttachmentVO } from './testStepAttachmentVO';


export interface TestStepVO { 
    attachments?: Array<TestStepAttachmentVO>;
    description?: string;
    executionStatus?: TestStepVO.ExecutionStatusEnum;
    executionStatusValue?: string;
    executionTime?: number;
    id?: number;
    objectName?: string;
    operation?: string;
    otherAttachments?: Array<TestStepAttachmentVO>;
    result?: string;
    snapshot?: TestStepAttachmentVO;
    testCaseId?: number;
    testCaseName?: string;
}
export namespace TestStepVO {
    export type ExecutionStatusEnum = 'PROGRESS' | 'PASSED' | 'FAILED' | 'WARNING';
    export const ExecutionStatusEnum = {
        PROGRESS: 'PROGRESS' as ExecutionStatusEnum,
        PASSED: 'PASSED' as ExecutionStatusEnum,
        FAILED: 'FAILED' as ExecutionStatusEnum,
        WARNING: 'WARNING' as ExecutionStatusEnum
    };
}
