/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TestSuite { 
    id: number;
    testExecutionId: number;
    readonly testExecutionName?: string;
    testSuiteName: string;
    executionStartTime: Date;
    executionEndTime?: Date;
    plannedTestCasesCount: number;
    readonly executedTestCasesCount?: number;
    readonly passedTestCasesCount?: number;
    readonly failedTestCasesCount?: number;
    readonly testCasesCountWithWarnings?: number;
}