/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TestSuite } from './testSuite';

export interface TestExecution {
    id: number;
    name: string;
    applicationId: number;
    readonly applicationName?: string;
    applicationVersion?: string;
    environmentId: number;
    readonly environmentName?: string;
    browser: string;
    operatingSystem?: string;
    systemIp: string;
    systemName: string;
    executedBy?: string;
    startTime: Date;
    endTime?: Date;
    readonly testSuites?: Array<TestSuite>;
    readonly targeted?: number;
    readonly executed?: number;
    readonly passed?: number;
    readonly failed?: number;
    readonly skipped?: number;
    readonly inProgress?: number;
}