/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TestStepAttachment { 
    id?: number;
    testStepId?: number;
    attachmentType: TestStepAttachment.AttachmentTypeEnum;
    fileName: string;
    fileContent: Array<string>;
    readonly attachmentRelativePath?: string;
    readonly attachmentTypeValue?: string;
}
export namespace TestStepAttachment {
    export type AttachmentTypeEnum = 'SNAPSHOT' | 'OTHER';
    export const AttachmentTypeEnum = {
        SNAPSHOT: 'SNAPSHOT' as AttachmentTypeEnum,
        OTHER: 'OTHER' as AttachmentTypeEnum
    };
}