/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TestCaseVO } from './testCaseVO';


export interface TestSuiteVO { 
    executedTestCasesCount?: number;
    executionEndTime?: Date;
    executionStartTime?: Date;
    failedTestCasesCount?: number;
    id?: number;
    passedTestCasesCount?: number;
    plannedTestCasesCount?: number;
    testCases?: Array<TestCaseVO>;
    testCasesCountWithWarnings?: number;
    testRunId?: number;
    testRunName?: string;
    testSuiteName?: string;
}
