/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TestStepAttachmentVO { 
    attachmentRelativePath?: string;
    attachmentType?: TestStepAttachmentVO.AttachmentTypeEnum;
    attachmentTypeValue?: string;
    fileContent?: string;
    fileName?: string;
    id?: number;
    testStepDescription?: string;
    testStepId?: number;
}
export namespace TestStepAttachmentVO {
    export type AttachmentTypeEnum = 'SNAPSHOT' | 'OTHER';
    export const AttachmentTypeEnum = {
        SNAPSHOT: 'SNAPSHOT' as AttachmentTypeEnum,
        OTHER: 'OTHER' as AttachmentTypeEnum
    };
}
