/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TestStepAttachment } from './testStepAttachment';

export interface TestStep { 
    executionStatus: TestStep.ExecutionStatusEnum;
    id: number;
    testCaseId: number;
    readonly testCaseName?: string;
    description: string;
    objectName?: string;
    operation?: string;
    result?: string;
    executionTime?: number;
    attachments?: Array<TestStepAttachment>;
    readonly executionStatusValue?: string;
}
export namespace TestStep {
    export type ExecutionStatusEnum = 'PROGRESS' | 'PASSED' | 'FAILED' | 'WARNING';
    export const ExecutionStatusEnum = {
        PROGRESS: 'PROGRESS' as ExecutionStatusEnum,
        PASSED: 'PASSED' as ExecutionStatusEnum,
        FAILED: 'FAILED' as ExecutionStatusEnum,
        WARNING: 'WARNING' as ExecutionStatusEnum
    };
}