/**
 * Reporting Tool
 * This is Reporting tool server.
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TestExecution } from './testExecution';
import { TestStep } from './testStep';

export interface TestCase { 
    executionStatus: TestCase.ExecutionStatusEnum;
    id: number;
    testSuiteId: number;
    readonly testSuiteName?: string;
    name: string;
    executionStartTime: Date;
    executionEndTime?: Date;
    readonly testSteps?: Array<TestStep>;
    testExecution?: TestExecution;
    readonly executionStatusValue?: string;
    readonly totalTestSteps?: number;
    readonly executedTestStepsCount?: number;
    readonly passedTestStepsCount?: number;
    readonly failedTestStepsCount?: number;
    readonly testStepsCountWithWarnings?: number;
    readonly executionTime?: number;
}
export namespace TestCase {
    export type ExecutionStatusEnum = 'PROGRESS' | 'PASSED' | 'FAILED' | 'WARNING';
    export const ExecutionStatusEnum = {
        PROGRESS: 'PROGRESS' as ExecutionStatusEnum,
        PASSED: 'PASSED' as ExecutionStatusEnum,
        FAILED: 'FAILED' as ExecutionStatusEnum,
        WARNING: 'WARNING' as ExecutionStatusEnum
    };
}